name: Server Side CI

on:
  push:
    branches: [main,ci-test]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: server

jobs:
  run:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls
      - run: yarn
      - run: yarn typecheck
      - run: yarn build
      - run: npx prettier --check
      - run: npx eslint
