name: Server Side CI

on:
  push:
    branches: [main,ci-test]
  pull_request:
    branches: [main]

jobs:
  defaults:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: server
  setup:
    runs-on: macos-latest
    steps:
      - run: yarn
  typecheck:
    needs: setup
    runs-on: macos-latest
    steps:
      - run: yarn typecheck
  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - run: yarn build
  check:
    needs: setup
    runs-on: macos-latest
    steps:
      - run: npx prettier --check
      - run: npx eslint
